### PR TITLE
Updates to make top level project

### PR DESCRIPTION
**Pull request by stevedlawrence**
- Removes all instances of "incubating"
- Removes the DISCLAIMER file and dialog in windows installer
- Updates README to match doap description
- Rewrap daffodil-cli readme so it's more readable

DAFFODIL-2470

### CODE REVIEW

**Comment by stevedlawrence** [comment]
List of things that must be updated before this should be merged to allow things to work:
* Daffodil accepted by the ASF board as a TLP
* Repos renamed to https://github.com/apache/daffodil and https://github.com/apache/daffodil-site
* Codecov updated to work with the new repo URLs (that might be automatic with the rename)
* Sonarcloud configuration
* daffodil directory created in dist.apache.org/repos/

**Review by tuxji — APPROVED** [review]
+1

Looks good, I couldn't find any mentions of incuba* left in the repo.  Might need to test Windows installer before doing a real release if not already tested.

**Comment by stevedlawrence** [comment]
> Might need to test Windows installer before doing a real release if not already tested.

Definitely. The release candidate builder that builds the windows exe currently works by cloning the repo, so it's a bit difficult to test things that haven't been committed, without hacking a bunch of stuff together. I'm thinking that before merging, I can make some tweaks so it clones my fork and that should give some confidence that it works before merging (haven't done that). But to be 100% sure it needs to be tested after merged. Fortunately, there's a --dry-run option so that should make it pretty easy to build a test release.

**Comment by stevedlawrence** [comment]
I spent some time this morning building/testing the windows MSI. And I did find fix a couple issues that are now fixed in the latest fixup commit. I am much more confident that the windows MSI installer works and has no references to incubation anymore.

We'll still want to test the release candiate script once repos are renamed and this commit is merged to make sure that all works, but I think the windows aspect of that should be good.

**Review by mbeckerle — APPROVED** [review]
+1 When we're ready to pull the trigger on this.

**Comment by stevedlawrence** [comment]
Note to self, we also need to update the following wiki pages once the transition is complete:

* [Code Contributor Workflow](https://cwiki.apache.org/confluence/display/DAFFODIL/Code+Contributor+Workflow)
* [Release Workflow](https://cwiki.apache.org/confluence/display/DAFFODIL/Release+Workflow)

**Comment by mbeckerle** [comment]
Checklist of external places that refer to Daffodil as incubator that will need updating:
I did a google web search for "apache daffodil (incubating)" and ran through the various returns there. 

These reference the github repo, so can't be updated until the repo location/name is updated:
* scaladex - https://index.scala-lang.org/apache/incubator-daffodil/daffodil-core/3.0.0?target=_2.12
* openhub - https://www.openhub.net/p/dfdl-daffodil

This also has mentions explicitly of "apache daffodil (incubating)"
* daffodil nifi - https://opensource.ncsa.illinois.edu/bitbucket/projects/DFDL/repos/daffodil-nifi/browse

I already updated github DFDLSchemas site, and references to daffodil (incubating) within individual schemas I searched and they're not there, or if they are, they're in a historic context where I don't think we need to update them. 

I verified the wikipedia page on DFDL does not mention "(incubating)" w.r.t. daffodil.

**Comment by stevedlawrence** [comment]
I'm not sure we have access to the NCSA repo anymore. The maintained NiFi Daffodil repo has moved to https://github.com/TresysTechnology/nifi-daffodil. I have just now updated that repo to remove the incubating.

**Comment by mbeckerle** [comment]
I definitely do not have write access to the ncsa repo, though I can login. Probably would be good to put a forwarding link in the README file. But if nobody has write access, then we can just let this fade away in time.

**Comment by stevedlawrence** [comment]
I did some testing with the release candidate script this morning. I renamed my forked github repos to "daffodil" and "daffodil-site" (I reccomend others do this too), and temporarily tweaked the release candidate script to build from my fork instead of from apache and ran a dry run. Only issue was the missing ``dist/{dev,release}/daffodil`` directories. I've created those and now the release candidate scripts works with no issues, and I didn't find any instances of "incubat*". All that's left I think is for INFRA to rename the apache github repos and I'm pretty confident this change can be safely merged.

**Comment by mbeckerle** [comment]
OpenHub has been updated.

Scaladex - according to https://github.com/scalacenter/scaladex-contrib it seems this site updates itself by pulling from maven central, so long as what is pushed there has an scm tag indicating where the source lives.

**Comment by mbeckerle** [comment]
I believe this means this won't update until a release is pushed to maven central that has source scm tag that does not specify "incubating-" in it.

**Comment by stevedlawrence** [comment]
Yeah, I think you're right. I have confirmed the new poms do have the new github URL, so once we do a release this should be fixed. 

Though github.com/apache/incubator-daffodil does redirect to github.com/apache/daffodil, so if scaladex can follow redirects, it might auto update?

**Comment by mbeckerle** [comment]
Furthermore, unfortunately, at Maven central, the link for source code for daffodil specifies the gitbox URL 
https://gitbox.apache.org/repos/asf/incubator-daffodil.git
And this fails. 

Moving this to a JIRA ticket https://issues.apache.org/jira/browse/DAFFODIL-2471

**Comment by jw3** [comment]
Non code update, the about line on the github page

image

**Comment by stevedlawrence** [comment]
Ah, good find. We could have infra fix this, but the better more future proof method is probably to add a [.asf.yml](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features) file. That let's us change the description, but also configure other aspects of github.

**Comment by stevedlawrence** [comment]
Just created PR #492 to hopefuly fix the description and allow us to configure gitbox/github more easily in the future.

**Pull request merged**
