### PR TITLE
Bump version for 3.8.0-SNAPSHOT development

### PR DESCRIPTION
**Pull request by stevedlawrence**

### CODE REVIEW

**Review by pkatlic — APPROVED** [review]
+1

**Review by tuxji — APPROVED** [review]
+1

**Comment by tuxji** [comment]
I noticed that the macOS build has a compilation error:

```log
[info] [cc, -c, /Users/runner/work/daffodil/daffodil/daffodil-codegen-c/src/main/resources/org/apache/daffodil/codegen/c/files/libcli/xml_writer.c, -o, /Users/runner/work/daffodil/daffodil/daffodil-codegen-c/target/streams/compile/ccSourceObjectMap/_global/streams/compile/libruntime.a/src/main/resources/org/apache/daffodil/codegen/c/files/libcli/xml_writer.c.o, -I/Users/runner/work/daffodil/daffodil/daffodil-codegen-c/src/main/resources/org/apache/daffodil/codegen/c/files/libcli, -I/Users/runner/work/daffodil/daffodil/daffodil-codegen-c/src/main/resources/org/apache/daffodil/codegen/c/files/libruntime, -Wall, -Wextra, -Wpedantic, -std=gnu11]
In file included from /Users/runner/work/daffodil/daffodil/daffodil-codegen-c/src/main/resources/org/apache/daffodil/codegen/c/files/libcli/xml_writer.c:20:
In file included from /Users/runner/work/daffodil/daffodil/daffodil-codegen-c/src/main/resources/org/apache/daffodil/codegen/c/files/libcli/xml_writer.h:25:
/Users/runner/work/daffodil/daffodil/daffodil-codegen-c/src/main/resources/org/apache/daffodil/codegen/c/files/libcli/stack.h:23:10: fatal error: 'mxml.h' file not found
#include <mxml.h>     // for mxml_node_t
         ^~~~~~~~
1 error generated.
```

The mxml library has recently released 4.0, 4.0.1, and 4.0.2 (around March 20 & 22).  When the CI workflow ran "brew install libmxml" to install the header file and library, it picked up the newly released 4.0.2 version:

```log
Run brew install libmxml
==> Downloading https://ghcr.io/v2/homebrew/core/libmxml/manifests/4.0.2
==> Fetching libmxml
==> Downloading https://ghcr.io/v2/homebrew/core/libmxml/blobs/sha256:98e1e1b8b65b2cabd74cd88dc9c6bc7c20b702729047bc80bb90a692ae8d4357
==> Pouring libmxml--4.0.2.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libmxml/4.0.2: 19 files, 1.8MB
```

I checked the mxml git repository and mxml.h is still there (it hasn't been renamed or moved).  I'm not sure what's going on (@pkatlic  may be able to find out more with his MacBook), but the quickest fix would be to change the workflow to install a previous version of mxml (v3.3.1 was the last version before v4.0 was released).  The Linux build also pins mxml to 3.x because it runs on Ubuntu 22.04, which doesn't roll packages to new versions (only adds security patches as needed).  This documentation describes how to make brew install a specific version of a package:

<https://www.slingacademy.com/article/homebrew-how-to-install-a-specific-version-of-a-package/>.

**Comment by stevedlawrence** [comment]
I noticed the failures too and opened DAFFODIL-2889. I saw a week or so ago but it went away, maybe the mxml upate hadn't been distributed yet.

I think you're right that the issue is related to mxml 4+ being found. Looking at a previous run that succeeded (https://github.com/stevedlawrence/daffodil/actions/runs/8542500456/job/23404272088) it found 3.3.1. I agree that pinning to an older version is probably the right thing to do.

**Pull request merged**
